import { ArrowRight, Building2, CheckCircle2, Eye, FileText, Headphones, HeartHandshake, ShieldCheck, Target, Users } from "lucide-react";
import Button from "../components/ui/Button";
import heroImage from "../assets/hero1.png";
import storyImage from "../assets/laptop-support.png";
import supportImage from "../assets/image2.png";

const trust = [[HeartHandshake, "Trusted Support", "Reliable and professional guidance"], [ShieldCheck, "Secure Process", "Your data is safe with us"], [Users, "Customer First", "Your peace of mind is our priority"]];
const reasons = [[ShieldCheck, "Expert Guidance", "Get help from experienced professionals."], [CheckCircle2, "Simple Process", "Easy and hassle-free query submission."], [FileText, "Transparent Updates", "Track your query status in real-time."], [Headphones, "Dedicated Support", "We're always here to assist you."]];

export default function About() {
  return <main className="about-page overflow-hidden bg-white">
    <section className="about-hero section-soft"><div className="section-shell py-12 md:py-16 lg:py-20"><div className="mx-auto grid max-w-[1450px] items-center gap-8 lg:grid-cols-[.95fr_1.05fr]"><div><p className="eyebrow">About Dispute Paisa</p><h1 className="mt-3 max-w-[630px] text-[40px] font-extrabold leading-[1.08] tracking-[-.055em] text-brand-900 md:text-[52px]">We’re Here to Make Banking Simpler, <span className="text-brand-500">Safer and Fairer.</span></h1><p className="mt-5 max-w-[620px] text-[15px] leading-7 text-slate-600">Dispute Paisa is a customer-first platform dedicated to helping individuals resolve banking issues with ease, transparency and expert support.</p><div className="mt-7 grid gap-4 sm:grid-cols-3">{trust.map(([Icon, title, copy]) => <div key={title} className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-brand-500 text-white"><Icon size={20} /></span><div><h3 className="text-xs font-extrabold text-brand-900">{title}</h3><p className="mt-1 text-[11px] leading-4 text-slate-500">{copy}</p></div></div>)}</div></div><div className="about-hero-image"><img src={heroImage} alt="Dispute Paisa banking support" /><span className="about-float-card"><ShieldCheck size={27} /> Resolve Banking Issues Easily</span></div></div><div className="about-stats mx-auto mt-8 grid max-w-[1450px] grid-cols-2 gap-y-5 rounded-2xl px-6 py-6 md:grid-cols-4 md:px-10">{[[FileText, "10K+", "Queries Raised"], [ShieldCheck, "99%", "Resolution Support"], [Users, "5000+", "Happy Customers"], [Building2, "All Major Banks", "Supported"]].map(([Icon, stat, label]) => <div key={stat} className="text-center md:border-r md:border-brand-200 last:border-0"><Icon className="mx-auto text-brand-500" size={27} /><strong className="mt-2 block text-xl font-extrabold text-brand-900">{stat}</strong><span className="text-[11px] font-semibold text-brand-900">{label}</span></div>)}</div></div></section>
    <section className="section-shell py-14 lg:py-16"><div className="mx-auto grid max-w-[1350px] gap-10 lg:grid-cols-2 lg:items-center"><img src={storyImage} alt="Dispute Paisa on laptop" className="about-story-image" /><div><p className="eyebrow">Our story</p><h2 className="mt-3 text-[36px] font-extrabold leading-[1.1] tracking-[-.045em] text-brand-900">Building a Fairer <span className="text-brand-500">Banking Experience</span></h2><p className="mt-5 text-sm leading-6 text-slate-600">Dispute Paisa was founded with a simple belief — every customer deserves to be heard. Banking issues can be frustrating, time-consuming and confusing. We bridge the gap between customers and banks through structured, transparent support.</p><Button href="/#query" className="mt-6">Our Purpose <ArrowRight size={16} /></Button></div></div><div className="mx-auto mt-9 grid max-w-[1350px] gap-5 md:grid-cols-2">{[[Target, "Our Mission", "To empower banking customers with easy access to dispute resolution support and ensure fair outcomes."], [Eye, "Our Vision", "To become India’s most trusted platform for banking dispute assistance, known for transparency and customer care."]].map(([Icon, title, copy]) => <article key={title} className="about-value-card"><span><Icon size={29} /></span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="section-shell pb-14 lg:pb-16"><div className="mx-auto max-w-[1350px] text-center"><p className="eyebrow justify-center">Why choose us</p><h2 className="mt-2 text-[35px] font-extrabold tracking-[-.045em] text-brand-900">More Than <span className="text-brand-500">Just Support</span></h2><p className="mt-2 text-sm text-slate-500">We go beyond basic assistance to give you a smooth and stress-free experience.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{reasons.map(([Icon, title, copy]) => <article key={title} className="about-reason"><span><Icon size={23} /></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section-shell pb-14 lg:pb-16"><div className="mx-auto grid max-w-[1350px] gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">How we help</p><h2 className="mt-3 text-[38px] font-extrabold leading-[1.1] tracking-[-.05em] text-brand-900">Supporting You <span className="text-brand-500">Every Step of the Way</span></h2><p className="mt-4 text-sm leading-6 text-slate-600">From understanding your issue to getting it resolved, Dispute Paisa stays with you throughout the process.</p><ul className="mt-6 space-y-3">{["Understand your concern", "Guide you with the right solution", "Coordinate with the concerned bank", "Keep you updated until resolution"].map((item) => <li key={item} className="flex items-center gap-3 text-sm font-bold text-brand-900"><CheckCircle2 size={20} className="text-brand-500" />{item}</li>)}</ul></div><img src={supportImage} alt="Customer support guidance" className="about-support-image" /></div></section>
    <section className="section-shell pb-12"><div className="about-cta mx-auto max-w-[1350px]"><div><h2>Let’s Resolve Your<br />Banking Issue <span>Together</span></h2><p>Take the first step towards a hassle-free banking experience.</p></div><Button variant="white" href="/#query">Raise a Query <ArrowRight size={18} /></Button></div></section>
  </main>;
}
